version: '3.8'

services:
  db: 
    container_name: recycle_chain_app_db
    image: postgres
    restart: always
    ports:
      - 2025:5432
    environment:
       POSTGRES_USER: postgres
       POSTGRES_DB: postgres
       POSTGRES_PASSWORD: password
    volumes:
      - db_data_recycle_chain_app:/var/lib/postgresql/data
volumes:
  db_data_recycle_chain_app: 

